site_name: webOS Docs
nav:
    - Home: index.md
    - Getting Started:
      - Activating a webOS Device: activate.md
      - Installing Apps on your webOS Device: appstores.md
      - Getting Online: online.md
      - Using the webOS Archive Proxy: proxysetup.md
    - Next Steps:
      - Shell Access: bash.md
      - Time Synchronization: timesync.md
      - Update Hosts: hosts.md
      - Build Your Own Apps: sdkpdk.md
theme:
  name: readthedocs
  favicon: images/icon.ico
  icon: 
    logo: material/book-check
  custom_dir: overrides